#!/usr/bin/env bash
# One-command setup: patches an MJ repo with the eslint plugin.
# Run from your MJ repo root:
#   curl -s https://raw.githubusercontent.com/pranavrao-BC/eslint-plugin-memberjunction/main/setup-mj.sh | bash
# Or if you have the plugin repo cloned:
#   bash /path/to/eslint-plugin-memberjunction/setup-mj.sh

set -euo pipefail

# Detect MJ repo root (look for turbo.json + packages/)
if [ ! -f "turbo.json" ] || [ ! -d "packages" ]; then
  echo "Error: Run this from the root of your MJ repo (the directory with turbo.json and packages/)."
  exit 1
fi

PLUGIN_DIR=""

# Check if the plugin is already cloned as a sibling
if [ -d "../eslint-plugin-memberjunction/dist/index.js" ]; then
  PLUGIN_DIR="$(cd ../eslint-plugin-memberjunction && pwd)"
  echo "Found plugin at $PLUGIN_DIR"
else
  # Clone and build
  echo "Cloning eslint-plugin-memberjunction..."
  git clone --depth 1 https://github.com/pranavrao-BC/eslint-plugin-memberjunction.git ../eslint-plugin-memberjunction 2>/dev/null || true
  PLUGIN_DIR="$(cd ../eslint-plugin-memberjunction && pwd)"
  echo "Building plugin..."
  (cd "$PLUGIN_DIR" && npm install --silent && npm run build --silent)
fi

# Symlink into node_modules so ESLint can find it
echo "Linking plugin into node_modules..."
mkdir -p node_modules/@memberjunction
ln -sf "$PLUGIN_DIR" node_modules/@memberjunction/eslint-plugin

# Drop a .eslintrc config if one doesn't exist
if [ ! -f ".eslintrc.mj.cjs" ]; then
  echo "Creating .eslintrc.mj.cjs..."
  cat > .eslintrc.mj.cjs << 'ESLINTRC'
// MJ Convention Linter — auto-generated by setup-mj.sh
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: { ecmaVersion: 2022, sourceType: 'module' },
  plugins: ['@memberjunction', '@typescript-eslint'],
  rules: {
    // -- Entity / Data Access --
    '@memberjunction/no-entity-get-set': 'warn',
    '@memberjunction/no-entity-spread': 'warn',
    '@memberjunction/no-direct-entity-new': 'warn',
    '@memberjunction/use-uuids-equal': 'warn',
    '@memberjunction/no-fields-with-entity-object': 'warn',
    // -- Performance / Correctness --
    '@memberjunction/no-runview-in-loop': 'warn',
    '@memberjunction/runview-check-success': 'warn',
    '@memberjunction/entity-save-check-result': 'warn',
    '@memberjunction/no-promise-all-runview': 'warn',
    '@memberjunction/prefer-simple-result-type': 'warn',
    // -- Angular --
    '@memberjunction/no-legacy-template-syntax': 'warn',
    '@memberjunction/for-requires-track': 'warn',
    '@memberjunction/prefer-inject-function': 'warn',
    '@memberjunction/no-ng-on-changes': 'warn',
    '@memberjunction/no-router-in-generic': 'warn',
    '@memberjunction/require-standalone-false': 'warn',
    // -- Type Safety --
    '@memberjunction/no-any-type': 'warn',
    '@memberjunction/no-action-call-action': 'warn',
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-unused-vars': 'off',  // off — too noisy to enable by default
    // -- Architecture --
    '@memberjunction/no-static-singleton': 'warn',
    '@memberjunction/no-cross-package-reexport': 'warn',
    '@memberjunction/no-enum-prefer-union': 'warn',
    '@memberjunction/no-kendo-icons': 'warn',
    '@memberjunction/no-legacy-template-syntax': 'warn',
  },
  ignorePatterns: ['node_modules/', 'dist/', '*.d.ts', '*.test.ts', '__tests__/', 'generated/'],
};
ESLINTRC
fi

echo ""
echo "Done! You can now run:"
echo ""
echo "  # Lint files you changed on this branch"
echo "  npx eslint --no-eslintrc -c .eslintrc.mj.cjs \$(git diff --name-only origin/next...HEAD -- '*.ts')"
echo ""
echo "  # Lint a specific file"
echo "  npx eslint --no-eslintrc -c .eslintrc.mj.cjs packages/MJCore/src/generic/someFile.ts"
echo ""
echo "  # Lint a whole package"
echo "  npx eslint --no-eslintrc -c .eslintrc.mj.cjs 'packages/MJServer/src/**/*.ts'"
echo ""
